-- ============================================================
-- Coffe Maya - Seed de datos iniciales
-- ============================================================
-- El usuario admin se crea via Supabase Auth (Dashboard o CLI).
-- El catálogo de productos (menú de la fonda) vive en la migración
-- 20260420162500_reemplazar_catalogo_con_menu_fonda.sql para que sea
-- la fuente de verdad tanto en local como al desplegar a Supabase remoto.
